name: 2024 Tests 🧪

on:
  push:
    paths:
      - "2024/**"

jobs:
  run:
    name: Test 2024 Solutions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🧾
        uses: actions/checkout@v4

      - name: Set Up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"

      - name: Build 🔨
        working-directory: ./2024/AoC2024
        run: dotnet build

      - name: Run Tests 🧪
        working-directory: ./2024/AoC2024.Tests
        run: dotnet test
